
services:

  redis:
    image: redis:alpine
    container_name: redis_container
    restart: always
    ports:
      - "6379:6379"
    networks:
      - app_network

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    networks:
      - app_network
    environment:
      - SERVER_IP=139.59.27.213
      - IPINFO_API_KEY=7699994f917ae1
      - REDIS_HOST=redis
    # depends_on:
    #   - frontend

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    networks:
      - app_network
    environment:
      - SERVER_IP=139.59.27.213
    depends_on:
      - backend

networks:
  app_network:
    driver: bridge

