version: "3.8"

services:
  redis:
    image: redis:alpine
    container_name: redis_container
    restart: always
    ports:
      - "6379:6379"
    networks:
      - app_network

  backend:
    build: ./backend
    image: girdhar005/cyderes-backend:latest
    ports:
      - "5000:5000"
    networks:
      - app_network
    env_file:
      - .env  # Loads values from .env file
    environment:
      - SERVER_IP=${SERVER_IP}
      - IPINFO_API_KEY=${IPINFO_API_KEY}
      - REDIS_HOST=redis

  frontend:
    build: ./frontend
    image: girdhar005/cyderes-frontend:latest
    ports:
      - "5173:5173"
    networks:
      - app_network
    env_file:
      - .env  # Loads values from .env file
    environment:
      - VITE_API_URL=${VITE_API_URL}
    depends_on:
      - backend

networks:
  app_network:
    driver: bridge
